### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by bbgfcc** [clovisphere/simple-flask-vagrant-setup#1]
When I stop the virtual machine and restart it, nginx gives me error 502.

I have reviewed the configuration of Nginx and the only weird thing I found is that the conf.d file is empty, not the nginx.conf.

I tried to do a zero installation with a new vagrant up and the error is repeated each time I stop the machine with "vagrant halt" and restart it with "vagrant up".

**Comment by clovisphere** [comment]
Hey @ZoomTeam, thanks for reporting the issue.

I just had a look, and it works fine on my end. Try to do a -

`vagrant reload --provision`

or

`vagrant up --provision` 

Let me know if that sorted the issue you are facing. I got rid of the **ansible** warnings, you'd pull latest code.

**Comment by clovisphere** [comment]
That should solved the 500 issue
